### ISSUE TITLE
Disappear off android store?

### ISSUE THREAD

**Issue by rmmeans** [mattprecious/prioritysms#10]
Hi! I've been using this app for several years and love it. I went to go re-install it tonight on a replacement phone (same android version, etc that I had before, on the same phone model) and noticed that I can't find the app any longer on the app store. Wondering if you removed it?

**Comment by mattprecious** [comment]
I doesn't work reliably anymore due to system changes so I unpublished it. I think if you've installed it before you should still be able to access it: https://play.google.com/store/apps/details?id=com.mattprecious.prioritysms
